import type { Page } from '@playwright/test'
import { test, expect } from './fixtures/account'

async function openChecker(page: Page) {
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.getByRole('group', { name: '生成・検証・判定の種類' }).getByRole('button', { name: '判定方法', exact: true }).click()
}

for (const [method, label] of [['special', '検証コード'], ['interactive', '対話用ジャッジ']] as const) {
  test(`${method} defaults to testlib for C++23 and preserves its saved protocol`, async ({ page }) => {
    await page.route('**/api/runtimes', route => route.fulfill({ json: { items: [{ id: 'cpp23-gcc', label: 'C++23' }, { id: 'python314', label: 'Python' }] } }))
    await Promise.all([page.waitForResponse('**/api/runtimes'), page.goto('/problems/new?fresh=1')])
    await page.getByLabel('問題のタイトル').fill('testlib形式の保存')
    await openChecker(page)
    await page.getByRole('combobox', { name: '判定方法', exact: true }).selectOption(method)
    await expect(page.getByLabel(`${label}の言語`)).toHaveValue('cpp23-gcc')
    await expect(page.getByLabel('判定コードの形式')).toHaveValue('testlib')
    await page.getByLabel(label, { exact: true }).fill('#include "testlib.h"\nint main(){}')
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
    await page.reload()
    await openChecker(page)
    await expect(page.getByLabel('判定コードの形式')).toHaveValue('testlib')
    await page.getByLabel(`${label}の言語`).selectOption('python314')
    await expect(page.getByLabel('判定コードの形式')).toHaveValue('legacy')
    await expect(page.getByLabel(label, { exact: true })).toContainText('#include "testlib.h"')
    await expect(page.getByLabel('判定コードの形式').locator('option')).toHaveCount(1)
  })
}

for (const [method, label] of [['special', '検証コード'], ['interactive', '対話用ジャッジ']] as const) {
  test(`${method} code survives switching to normal and back`, async ({ page }) => {
    await page.route('**/api/runtimes', route => route.fulfill({ json: { items: [{ id: 'cpp17', label: 'C++17' }, { id: 'python314', label: 'Python' }] } }))
    await page.goto('/problems/new?fresh=1')
    await page.getByLabel('問題のタイトル').fill('判定方法の切り替え')
    await openChecker(page)
    const selector = page.getByRole('combobox', { name: '判定方法', exact: true })
    await selector.selectOption(method)
    await page.getByLabel(`${label}の言語`).selectOption('python314')
    for (const source of ['print(42)', 'print(43)']) {
      await page.getByLabel(label, { exact: true }).fill(source)
      await selector.selectOption('normal')
      await expect(page.getByLabel(label, { exact: true })).toHaveCount(0)
      const saved = page.waitForResponse(response => response.url().includes('/api/my/problems/') && response.request().method() === 'PUT')
      await page.getByRole('button', { name: '保存', exact: true }).click()
      const body = (await saved).request().postDataJSON()
      expect(body.draft.checker).toBeNull()
      expect(body.draft.interactor).toBeNull()
      await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
      await page.getByRole('button', { name: '問題文', exact: true }).click()
      await openChecker(page)
      await selector.selectOption(method)
      await expect(page.getByLabel(`${label}の言語`)).toHaveValue('python314')
      await expect(page.getByLabel(label, { exact: true })).toHaveText(source)
    }
  })
}

test('checker languages match submissions and settings survive saving and reload', async ({ page }, testInfo) => {
  await page.route('**/api/runtimes', route => route.fulfill({ json: { items: [{ id: 'cpp17', label: 'C++17' }, { id: 'python314', label: 'Python' }] } }))
  await Promise.all([page.waitForResponse('**/api/runtimes'), page.goto('/problems/new')])
  await page.getByLabel('問題のタイトル').fill('構築問題')
  await openChecker(page)
  await page.getByRole('combobox', { name: '判定方法', exact: true }).selectOption({ label: 'スペシャルジャッジ' })
  await expect(page.getByLabel('検証コードの言語').locator('option')).toHaveText(['C++17', 'Python'])
  await page.getByLabel('検証コードの言語').selectOption('python314')
  await page.getByLabel('検証コード', { exact: true }).fill('import sys\nassert int(sys.stdin.read()) == 7')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
  const id = new URL(page.url()).searchParams.get('problem')!
  expect(id).toBeTruthy()
  await Promise.all([page.waitForResponse('**/api/runtimes'), page.reload()])
  await openChecker(page)
  await expect(page.getByLabel('検証コードの言語')).toHaveValue('python314')
  await expect(page.getByLabel('検証コード', { exact: true })).toContainText('assert int(sys.stdin.read()) == 7')
  await expect(page.getByRole('button', { name: '問題ページで提出する', exact: true })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('checker-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 375, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('checker-mobile.png'), fullPage: true })
  await page.getByRole('combobox', { name: '判定方法', exact: true }).selectOption({ label: '通常判定（空白区切りで比較）' })
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
  await page.reload()
  await openChecker(page)
  await expect(page.getByLabel('検証コードの言語')).toHaveCount(0)
})

test('interactive judging saves the selected language and mutually excludes special judging', async ({ page }) => {
  await page.route('**/api/runtimes', route => route.fulfill({ json: { items: [{ id: 'cpp23-gcc', label: 'C++23' }, { id: 'python314', label: 'Python' }] } }))
  await Promise.all([page.waitForResponse('**/api/runtimes'), page.goto('/problems/new')])
  await page.getByLabel('問題のタイトル').fill('対話問題')
  await openChecker(page)
  await page.getByRole('combobox', { name: '判定方法', exact: true }).selectOption('interactive')
  await expect(page.getByLabel('対話用ジャッジの言語').locator('option')).toHaveText(['C++23', 'Python'])
  await page.getByLabel('対話用ジャッジの言語').selectOption('python314')
  await page.getByLabel('対話用ジャッジ', { exact: true }).fill('print(10, flush=True)\nassert int(input()) == 20')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
  await page.reload()
  await openChecker(page)
  await expect(page.getByRole('combobox', { name: '判定方法', exact: true })).toHaveValue('interactive')
  await expect(page.getByLabel('対話用ジャッジ', { exact: true })).toContainText('assert int(input()) == 20')
  await expect(page.getByText('各ケースCPU 5秒・256 MiB', { exact: false })).toBeVisible()
  await page.setViewportSize({ width: 375, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('combobox', { name: '判定方法', exact: true }).selectOption('special')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
  await page.reload()
  await openChecker(page)
  await expect(page.getByRole('combobox', { name: '判定方法', exact: true })).toHaveValue('special')
  await expect(page.getByLabel('検証コードの言語')).toHaveValue('python314')
})

test('judge tab saves the draft and opens the problem page to submit', async ({ page }) => {
  await page.goto('/problems/new?fresh=1')
  await page.getByLabel('問題のタイトル').fill('判定を試す')
  await openChecker(page)
  await page.getByRole('combobox', { name: '判定方法', exact: true }).selectOption('special')
  const open = page.getByRole('button', { name: '問題ページで提出する', exact: true })
  await expect(open).toBeDisabled()
  await page.getByLabel('検証コード', { exact: true }).fill('int main(){}')
  const saved = page.waitForRequest(request => request.method() === 'PUT' && /^\/api\/my\/problems\/[^/]+$/.test(new URL(request.url()).pathname))
  await open.click()
  expect((await saved).postDataJSON().draft.checker.source).toBe('int main(){}')
  await expect(page).toHaveURL(/\/problems\/[0-9a-f-]{36}#submission-title$/)
})
