import { expect, test } from './fixtures/account'

test('generators append numbered inputs, replace outputs, persist code and retain cases on failure', async ({ page }) => {
  const requests: Record<string, any>[] = []
  let verdict = 'AC'
  await page.route('**/api/my/submissions', async route => {
    const body = route.request().postDataJSON()
    requests.push(body)
    await route.fulfill({ json: { id: 'generation-job', status: 'QUEUED' } })
  })
  await page.route('**/api/my/submissions/generation-job', route => {
    const mode = requests.at(-1)?.generation.mode
    return route.fulfill({ json: { id: 'generation-job', status: 'DONE', result: { verdict, compileLog: verdict === 'CE' ? 'syntax error' : undefined,
      cases: mode === 'input' ? [{ output: '7 8\n' }, { output: '' }] : [{ output: '15\n' }, { output: '' }] } } })
  })
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.getByLabel('入力生成のコード', { exact: true }).fill('#include <iostream>\nint main(){int n;std::cin>>n;std::cout<<n;}')
  await page.getByLabel('開始ケース番号').fill('7')
  await page.getByLabel('生成件数').fill('2')
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  // While generating, other modes stay locked but the running mode and the judge tab remain reachable.
  for (const name of ['出力生成', '入力検証']) {
    await expect(page.getByRole('button', { name, exact: true })).toBeDisabled()
  }
  await expect(page.getByRole('button', { name: '入力生成', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: '判定方法', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByRole('button', { name: 'テストケースを追加' })).toBeDisabled()
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await expect(page.getByText('2件の入力を追加しました。')).toBeVisible()
  expect(requests[0]?.generation).toEqual({ mode: 'input', start: 7, count: 2 })
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('7 8\n')
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.getByRole('button', { name: '出力生成', exact: true }).click()
  await page.getByLabel('出力生成のコード', { exact: true }).fill('#include <iostream>\nint main(){int a,b;std::cin>>a>>b;std::cout<<a+b;}')
  await expect(page.locator('.generator input[type=number]')).toHaveCount(0)
  page.on('dialog', async dialog => {
    expect(dialog.message()).toBe('全2件のテストケースの出力を生成結果で上書きしますか？')
    await dialog.accept()
  })
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await expect(page.getByText('2件の出力を更新しました。')).toBeVisible()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('15\n')
  expect(requests[1]?.generation).toEqual({ mode: 'output', start: 1, count: 2 })
  verdict = 'CE'
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await expect(page.locator('.generator [role=alert]')).toContainText('syntax error')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('15\n')
  await page.getByRole('button', { name: 'generated_8.txt', exact: true }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('')
  await expect(page.getByRole('status').filter({ hasText: '保存済み' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await expect(page.getByLabel('入力生成のコード')).toContainText('std::cin>>n')
  await page.getByRole('button', { name: '出力生成', exact: true }).click()
  await expect(page.getByLabel('出力生成のコード')).toContainText('std::cout<<a+b')
  await page.route('**/api/my/submissions/generation-job', route => route.fulfill({ json: { status: 'DONE', result: { verdict: 'AC', cases: [{ outputFile: { id: '33333333-3333-4333-8333-333333333333', size: 16 << 20, sha256: 'a'.repeat(64) } }, { output: '' }] } } }))
  await page.route('**/api/my/problems/*/test-files/*/complete', route => route.fulfill({ status: 400, json: {} }))
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await expect(page.locator('.generator [role=alert]')).toBeVisible()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('15\n')
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.setViewportSize({ width: 375, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('16 MiB files are applied by reference and the complete set stays within 512 MiB', async ({ page }) => {
  const { createHash } = await import('node:crypto')
  const content = `${'x'.repeat(1023)}\n`.repeat(16384)
  const size = Buffer.byteLength(content)
  const sha256 = createHash('sha256').update(content).digest('hex')
  let next = 1, completed = 0, downloads = 0
  let savedCases: { inputFile?: { size: number }, input: string }[] = []
  await page.route('**/api/my/problems/*', async route => {
    if (route.request().method() === 'PUT') savedCases = route.request().postDataJSON().draft.testCases
    await route.fallback()
  })
  await page.route('**/api/my/submissions', route => {
    const count = route.request().postDataJSON().generation.count
    const cases = Array.from({ length: count }, () => ({ outputFile: { id: `33333333-3333-4333-8333-${String(next++).padStart(12, '0')}`, size, sha256 } }))
    return route.fulfill({ json: { status: 'DONE', result: { verdict: 'AC', cases } } })
  })
  await page.route('**/api/my/problems/*/test-files/*/complete', route => {
    completed++
    const id = new URL(route.request().url()).pathname.split('/').at(-2)
    return route.fulfill({ json: { id, size, sha256 } })
  })
  await page.route('**/api/my/problems/*/test-files/*', route => route.fulfill({ json: { url: 'https://generated.example/file', size, sha256 } }))
  await page.route('https://generated.example/file', route => { downloads++; return route.fulfill({ contentType: 'text/plain', body: content }) })
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.getByLabel('入力生成のコード').fill('int main(){}')
  await page.getByLabel('生成件数').fill('32')
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await expect(page.getByText('32件の入力を追加しました。')).toBeVisible()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.locator('.test-data-editor').first().locator('.pane-heading span')).toContainText('16,777,216 / 16,777,216 bytes')
  await expect.poll(() => savedCases.length).toBe(32)
  expect(savedCases.every(item => item.inputFile?.size === size && item.input === '')).toBe(true)
  expect(completed).toBe(32)
  await expect.poll(() => downloads).toBe(1)
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.getByLabel('生成件数').fill('1')
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  await expect(page.locator('.generator [role=alert]')).toContainText('512 MiB')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.locator('.case-files li')).toHaveCount(32)
  expect(completed).toBe(32)
  expect(savedCases.length).toBe(32)
})

test('sidebar opens the generator workspace and links to its public guide', async ({ page }, testInfo) => {
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByRole('heading', { name: '生成・検証・判定', exact: true })).not.toBeVisible()
  const menu = page.getByRole('navigation', { name: '問題作成メニュー' })
  await menu.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await expect(menu.getByRole('button', { name: '生成・検証・判定', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('heading', { name: '生成・検証・判定', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: /入出力生成と入力検証の使い方/ })).toHaveAttribute('href', '/blog/generator-guide')
  await page.getByLabel('入力生成のコード').fill('int main(){}')
  await page.getByLabel('開始ケース番号').fill('7')
  await page.getByRole('button', { name: 'テストケースを確認' }).click()
  await expect(page.getByRole('heading', { name: /テストケース/ })).toBeVisible()
  await menu.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await expect(page.getByLabel('開始ケース番号')).toHaveValue('7')
  await expect(page.getByLabel('入力生成のコード')).toContainText('int main(){}')
  const modes = page.getByRole('group', { name: '生成・検証・判定の種類' })
  await expect(modes.getByRole('button')).toHaveText(['入力生成', '出力生成', '入力検証', '判定方法'])
  await expect(modes.getByRole('button', { pressed: true })).toHaveText('入力生成')
  await modes.getByRole('button', { name: '出力生成', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(modes.getByRole('button', { pressed: true })).toHaveText('出力生成')
  await page.getByLabel('出力生成のコード').fill('int main(){return 0;}')
  await modes.getByRole('button', { name: '入力検証', exact: true }).click()
  await expect(modes.getByRole('button', { pressed: true })).toHaveText('入力検証')
  await expect(page.getByLabel('入力検証のコード')).toBeVisible()
  await modes.getByRole('button', { name: '出力生成', exact: true }).click()
  await expect(page.getByLabel('出力生成のコード')).toContainText('int main(){return 0;}')
  await modes.getByRole('button', { name: '判定方法', exact: true }).click()
  await expect(modes.getByRole('button', { pressed: true })).toHaveText('判定方法')
  await expect(page.getByRole('combobox', { name: '判定方法', exact: true })).toBeVisible()
  await expect(page.getByLabel('出力生成のコード')).toBeHidden()
  await modes.getByRole('button', { name: '入力生成', exact: true }).click()
  await expect(page.getByLabel('入力生成のコード')).toContainText('int main(){}')
  // The I/O spec starts collapsed and stays open across tabs once expanded.
  await expect(page.getByText('ケース番号（整数1個）')).toBeHidden()
  await page.getByText('入力生成の仕様', { exact: true }).click()
  await expect(page.getByText('ケース番号（整数1個）')).toBeVisible()
  await modes.getByRole('button', { name: '出力生成', exact: true }).click()
  await expect(page.getByText('そのケースの出力を置き換えます')).toBeVisible()
  await modes.getByRole('button', { name: '入力生成', exact: true }).click()
  for (const width of [375, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    for (const button of await modes.getByRole('button').all()) await expect(button).toBeInViewport()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`generator-${width}.png`), fullPage: true })
  }
  await page.goto('/blog/generator-guide')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('入出力生成と入力検証の使い方')
  await expect(page.locator('article pre')).toHaveCount(3)
  await expect(page.locator('article')).toContainText('512 MiB')
  await expect(page.locator('article')).toContainText('std::cin >> case_number')
  await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href', 'https://judge.example/blog/generator-guide')
  await page.goto('/blog')
  await expect(page.getByRole('link', { name: '入出力生成と入力検証の使い方', exact: true })).toBeVisible()
})

test('input validation reports each case without changing test data and persists its code', async ({ page }) => {
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByLabel('入力', { exact: true }).fill('invalid input')
  await page.getByLabel('出力', { exact: true }).fill('keep output')
  let request: any
  await page.route('**/api/my/submissions', async route => {
    request = route.request().postDataJSON()
    await route.fulfill({ json: { id: 'validation', status: 'DONE', result: { verdict: 'RE', passed: 0, total: 1, cases: [{ name: 'case', verdict: 'RE' }] } } })
  })
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.getByRole('button', { name: '入力検証', exact: true }).click()
  await page.getByLabel('入力検証のコード').fill('int main(){return 1;}')
  await page.getByRole('button', { name: '検証する', exact: true }).click()
  await expect(page.getByRole('table', { name: '入力検証の結果' })).toContainText('不合格')
  await expect(page.getByRole('status').filter({ hasText: '1件中0件が合格' })).toBeVisible()
  expect(request.generation).toEqual({ mode: 'validation', start: 1, count: 1 })
  await page.getByRole('button', { name: 'テストケースを確認' }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('invalid input')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('keep output')
  await expect(page.getByRole('status').filter({ hasText: '保存済み' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.getByRole('button', { name: '入力検証', exact: true }).click()
  await expect(page.getByLabel('入力検証のコード')).toContainText('return 1;')
  await page.route('**/api/my/submissions', route => route.fulfill({ json: { id: 'validation', status: 'DONE', result: { verdict: 'AC', passed: 1, total: 1, cases: [{ verdict: 'AC' }] } } }))
  await page.getByRole('button', { name: '検証する', exact: true }).click()
  await expect(page.getByRole('table', { name: '入力検証の結果' }).getByRole('cell', { name: '合格', exact: true })).toBeVisible()
  await page.getByLabel('入力検証のコード').fill('int main(){return 0;}')
  await expect(page.getByRole('table', { name: '入力検証の結果' })).toHaveCount(0)
  await page.getByRole('button', { name: 'テストケースを確認' }).click()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.route('**/api/my/submissions', route => {
    request = route.request().postDataJSON()
    return route.fulfill({ json: { status: 'DONE', result: { verdict: 'AC', cases: [{ verdict: 'AC' }, { verdict: 'AC' }] } } })
  })
  await expect(page.locator('.generator input[type=number]')).toHaveCount(0)
  await page.getByRole('button', { name: '検証する', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: '2件中2件が合格' })).toBeVisible()
  expect(request.generation).toEqual({ mode: 'validation', start: 1, count: 2 })
})

test('generation frequency limit displays the wait time', async ({ page }) => {
  await page.route('**/api/my/submissions', route => route.fulfill({ status: 429, json: { data: { code: 'submission_rate_limited', retryAfter: 75 } } }))
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
  await page.getByLabel('入力生成のコード', { exact: true }).fill('int main(){}')
  await page.getByRole('button', { name: '生成する', exact: true }).click()
  const alert = page.locator('.generator [role=alert]')
  await expect(alert).toHaveText('提出頻度制限に到達しました。75秒後に再度試してください。')
  await expect(alert).toHaveCSS('background-color', 'rgb(255, 243, 242)')
})

for (const mode of ['output', 'validation'] as const) {
  test(`${mode} requires existing cases without asking for a range`, async ({ page }) => {
    let submitted = false
    await page.route('**/api/my/submissions', route => { submitted = true; return route.abort() })
    await page.goto('/problems/new')
    await page.getByRole('button', { name: '生成・検証・判定', exact: true }).click()
    await page.getByRole('button', { name: mode === 'output' ? '出力生成' : '入力検証', exact: true }).click()
    await expect(page.locator('.generator input[type=number]')).toHaveCount(0)
    await page.getByRole('button', { name: mode === 'output' ? '生成する' : '検証する', exact: true }).click()
    await expect(page.locator('.generator [role=alert]')).toHaveText('テストケースを追加してから実行してください。')
    expect(submitted).toBe(false)
  })
}
