import { expect, test } from './fixtures/account'

test('difficulty picker shows grades and supports keyboard selection and persistence', async ({ page }, testInfo) => {
  await page.goto('/problems/new')
  const picker = page.getByRole('combobox', { name: '難易度（作成者設定）' })
  await picker.click()
  await expect(page.getByRole('option')).toHaveCount(11)
  await expect(page.getByRole('listbox').locator('.difficulty-dot')).toHaveCount(9)
  await expect(page.getByRole('option', { name: 'Lv.10', exact: true }).locator('svg')).toBeVisible()
  await page.getByRole('option', { name: 'Lv.5', exact: true }).click()
  await expect(picker.locator('.difficulty-dot')).toHaveCSS('background-color', 'rgb(0, 184, 212)')
  await picker.press('ArrowDown')
  await picker.press('End')
  await picker.press('Enter')
  await expect(picker).toContainText('Lv.10')
  await expect(picker.locator('svg')).toBeVisible()
  await picker.press('ArrowDown')
  await picker.press('Home')
  await picker.press('Escape')
  await expect(picker).toContainText('Lv.10')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  await page.reload()
  await expect(picker).toContainText('Lv.10')
  for (const width of [1280, 375]) {
    await page.setViewportSize({ width, height: 900 })
    if (width < 960) await page.getByRole('button', { name: '問題設定', exact: true }).click()
    await picker.click()
    await expect(page.getByRole('listbox')).toBeInViewport()
    await page.screenshot({ path: testInfo.outputPath(`difficulty-${width}.png`), fullPage: true })
    await page.getByLabel('問題のタイトル', { exact: true }).click()
    await expect(page.getByRole('listbox')).toHaveCount(0)
  }
  await picker.click()
  await picker.press('Home')
  await picker.press('Enter')
  await expect(picker).toContainText('未設定')
  await picker.click()
  await picker.press('Tab')
  await expect(page.getByRole('listbox')).toHaveCount(0)
})

test('large test data renders only visible lines and names are unique', async ({ page }) => {
  const { createHash } = await import('node:crypto')
  const content = Array.from({ length: 200_000 }, (_, i) => String(i)).join('\n')
  const file = { id: '33333333-3333-4333-8333-333333333333', size: Buffer.byteLength(content), sha256: createHash('sha256').update(content).digest('hex') }
  await page.route('**/api/my/problems/*/test-files', route => {
    expect(route.request().postDataJSON()).toEqual({ size: file.size, sha256: file.sha256 })
    return route.fulfill({ json: { id: file.id, url: 'https://uploads.example/large.txt', headers: {} } })
  })
  await page.route('https://uploads.example/large.txt', route => {
    expect(route.request().method()).toBe('PUT')
    expect(route.request().postDataBuffer()).toEqual(Buffer.from(content))
    return route.fulfill({ status: 200 })
  })
  await page.route('**/api/my/problems/*/test-files/*/complete', route => route.fulfill({ json: file }))
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  const input = page.getByLabel('入力', { exact: true })
  await page.locator('.test-data-editor input[type=file]').first().setInputFiles({ name: 'large.txt', mimeType: 'text/plain', buffer: Buffer.from(content) })
  const scroller = page.locator('.test-data-editor').first().locator('.cm-scroller')
  await expect(page.locator('.test-data-editor').first().locator('.pane-heading span')).toContainText(`${Buffer.byteLength(content).toLocaleString('en-US')} / 16,777,216 bytes`)
  await scroller.evaluate(element => { element.scrollTop = element.scrollHeight })
  await expect(input).toContainText('199999')
  expect(await page.locator('.test-data-editor').first().locator('.cm-line').count()).toBeLessThan(100)
  await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
  await input.fill('1\n2\n3')
  await expect(input.locator('.cm-line')).toHaveText(['1', '2', '3'])
  await expect(page.locator('.test-data-editor').first().locator('.pane-heading span')).toContainText('5 / 16,777,216 bytes')
  await page.getByLabel('テストケース名 1', { exact: true }).fill('sample')
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByLabel('テストケース名 2', { exact: true }).fill('sample')
  await expect(page.locator('.test-case-editor [role="alert"]')).toContainText('重複')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'dirty')
  await page.getByLabel('テストケース名 2', { exact: true }).fill('large')
  await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
})

for (const width of [320, 375, 414, 768, 1280]) {
  test(`one file selection switches both editors at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/problems/new')
    const title = page.locator('#problem-title')
    const difficulty = page.getByLabel('難易度（作成者設定）')
    const time = page.locator('#time-limit')
    await expect(difficulty).toBeEnabled()
    expect(await title.evaluate(element => !!(element.compareDocumentPosition(document.querySelector('#problem-difficulty')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
    expect(await difficulty.evaluate(element => !!(element.compareDocumentPosition(document.querySelector('#time-limit')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
    if (width === 1280) {
      expect((await title.boundingBox())!.x).toBeLessThan((await difficulty.boundingBox())!.x)
      expect((await difficulty.boundingBox())!.x).toBeLessThan((await time.boundingBox())!.x)
      expect((await difficulty.boundingBox())!.y).toBe((await time.locator('..').boundingBox())!.y)
    }
    await page.getByRole('button', { name: 'テストケース', exact: true }).click()
    await page.getByRole('button', { name: 'テストケースを追加' }).click()
    await page.getByLabel('テストケース名 1', { exact: true }).fill('sample.txt')
    await page.getByLabel('入力', { exact: true }).fill('3 5')
    await page.getByLabel('出力', { exact: true }).fill('8')
    await page.getByRole('button', { name: 'テストケースを追加' }).click()
    await page.getByLabel('テストケース名 2', { exact: true }).fill('large.txt')
    await page.getByLabel('入力', { exact: true }).fill('100 200')
    await page.getByLabel('出力', { exact: true }).fill('300')
    const files = page.getByRole('navigation', { name: 'テストケース一覧' })
    await files.getByRole('button', { name: 'sample.txt', exact: true }).click()
    await expect(page.getByLabel('入力', { exact: true })).toHaveText('3 5')
    await expect(page.getByLabel('出力', { exact: true })).toHaveText('8')
    await expect(page.locator('.test-data-editor .cm-editor')).toHaveCount(2)
    await expect(page.getByRole('button', { name: 'ファイルを選択', exact: true })).toHaveCount(2)
    for (const input of await page.locator('.test-data-editor input[type=file]').all()) await expect(input).toBeHidden()
    const chooserPromise = page.waitForEvent('filechooser')
    await page.getByRole('button', { name: 'ファイルを選択', exact: true }).first().click()
    await (await chooserPromise).setFiles({ name: 'sample.txt', mimeType: 'text/plain', buffer: Buffer.from('3 5') })
    await expect(page.getByLabel('入力', { exact: true })).toHaveText('3 5')
    await files.getByRole('button', { name: 'large.txt', exact: true }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByLabel('入力', { exact: true })).toHaveText('100 200')
    await expect(page.getByLabel('出力', { exact: true })).toHaveText('300')
    await expect(files.getByRole('button', { name: 'large.txt', exact: true })).toHaveAttribute('aria-current', 'true')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`shared-files-${width}.png`), fullPage: true })
    page.on('dialog', dialog => dialog.accept())
    await page.getByRole('button', { name: 'ケース2を削除' }).click()
    await expect(page.getByLabel('入力', { exact: true })).toHaveText('3 5')
    await expect(page.getByLabel('出力', { exact: true })).toHaveText('8')
    await page.getByRole('button', { name: 'ケース1を削除' }).click()
    await expect(page.locator('.test-data-editor .cm-editor')).toHaveCount(0)
    await expect(page.getByText('テストケースはまだありません。')).toBeVisible()
  })
}

test.describe('small touch screens', () => {
  test.use({ hasTouch: true, isMobile: true })
  for (const viewport of [{ width: 358, height: 567 }, { width: 312, height: 553 }, { width: 667, height: 375 }]) {
    test(`can add and edit test cases at ${viewport.width}x${viewport.height}`, async ({ page }, testInfo) => {
      await page.setViewportSize(viewport)
      await page.goto('/problems/new')
      for (const section of ['問題文', 'テストケース', '生成と検証', '判定方法', '解説']) {
        await page.getByRole('button', { name: section, exact: true }).click()
        const save = (await page.getByRole('button', { name: '保存', exact: true }).boundingBox())!
        expect(viewport.width - save.x - save.width).toBeLessThanOrEqual(12)
      }
      await page.getByRole('button', { name: 'テストケース', exact: true }).click()
      await page.getByRole('button', { name: 'テストケースを追加', exact: true }).click()
      await page.getByLabel('テストケース名 1', { exact: true }).fill('sample.txt')
      for (const [label, text] of [['入力', '3 5\n'], ['出力', '8\n']]) {
        const editor = page.getByRole('textbox', { name: label, exact: true })
        const surface = editor.locator('xpath=ancestor::div[contains(@class,"code-surface")]')
        expect((await surface.boundingBox())!.height).toBeGreaterThanOrEqual(200)
        await surface.scrollIntoViewIfNeeded()
        const visibleHeight = await surface.evaluate(element => {
          let top = 0, bottom = innerHeight
          for (let parent: Element | null = element; parent; parent = parent.parentElement) {
            const bounds = parent.getBoundingClientRect()
            top = Math.max(top, bounds.top)
            bottom = Math.min(bottom, bounds.bottom)
          }
          return bottom - top
        })
        expect(visibleHeight).toBeGreaterThanOrEqual(200)
        await editor.fill(text)
        await expect(editor).toHaveText(text.trim())
        await page.screenshot({ path: testInfo.outputPath(`${label}.png`), fullPage: true })
      }
      await page.getByRole('button', { name: 'テストケースを追加', exact: true }).click()
      await page.getByLabel('テストケース名 2', { exact: true }).fill('large.txt')
      await page.getByRole('textbox', { name: '入力', exact: true }).fill('100 200')
      await page.getByRole('textbox', { name: '出力', exact: true }).fill('300')
      await page.getByRole('navigation', { name: 'テストケース一覧' }).getByRole('button', { name: 'sample.txt', exact: true }).click()
      await expect(page.getByRole('textbox', { name: '入力', exact: true })).toHaveText('3 5')
      await expect(page.getByRole('textbox', { name: '出力', exact: true })).toHaveText('8')
      await page.getByRole('button', { name: '保存', exact: true }).click()
      await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
      await page.reload()
      await page.getByRole('button', { name: 'テストケース', exact: true }).click()
      await expect(page.getByRole('textbox', { name: '入力', exact: true })).toHaveText('3 5')
      await expect(page.getByRole('textbox', { name: '出力', exact: true })).toHaveText('8')
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight)).toBe(true)
    })
  }
})

test('case limit stays at 100 when TL changes', async ({ page }) => {
  await page.goto('/problems/new')
  await page.locator('#time-limit').fill('5000')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  const add = page.getByRole('button', { name: 'テストケースを追加' })
  for (let i = 0; i < 100; i++) await add.click()
  await expect(add).toBeDisabled()
  await expect(page.locator('#test-cases-title')).toContainText('100 / 100件')
  await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
  await page.getByRole('button', { name: '問題文', exact: true }).click()
  await page.locator('#time-limit').fill('100')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(add).toBeDisabled()
  await expect(page.locator('#test-cases-title')).toContainText('100 / 100件')
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'ケース1を削除' }).click()
  await expect(add).toBeEnabled()
  await expect(page.locator('.case-files li')).toHaveCount(99)
  await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
})

test('500,000 ten-digit integers are stored as an immutable large test file', async ({ page }) => {
  const fileId = '33333333-3333-4333-8333-333333333333'
  const content = `500000\n${Array(500_000).fill('1000000000').join(' ')}\n`
  const size = Buffer.byteLength(content)
  expect(size).toBe(5_500_007)
  let digest = ''
  let uploaded = 0
  await page.route(/\/api\/my\/problems\/[^/]+\/test-files$/, async route => {
    const body = route.request().postDataJSON()
    digest = body.sha256
    expect(body.size).toBe(size)
    await route.fulfill({ json: { id: fileId, url: 'https://s3.example.test/file', headers: { 'content-type': 'text/plain; charset=utf-8', 'x-amz-checksum-sha256': digest, 'x-amz-tagging': 'status=pending' } } })
  })
  await page.route(new RegExp(`/api/my/problems/[^/]+/test-files/${fileId}/complete$`), route => route.fulfill({ json: { id: fileId, size, sha256: digest } }))
  await page.route(new RegExp(`/api/my/problems/[^/]+/test-files/${fileId}$`), route => route.fulfill({ json: { url: 'https://s3.example.test/file', size, sha256: digest } }))
  await page.route('https://s3.example.test/file', async route => {
    const headers = { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*', 'access-control-allow-methods': 'GET,PUT' }
    if (route.request().method() === 'PUT') {
      uploaded = route.request().postDataBuffer()?.length ?? 0
      await route.fulfill({ status: 200, headers })
    } else {
      await route.fulfill({ status: 200, headers, body: Buffer.from(content) })
    }
  })
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.locator('.test-data-editor input[type=file]').first().setInputFiles({ name: 'large.txt', mimeType: 'text/plain', buffer: Buffer.from(content) })
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('[data-save-state]')).toHaveAttribute('data-save-state', 'saved')
  expect(uploaded).toBe(size)
  expect(size).toBeLessThan(16 * 1024 * 1024)
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.locator('.test-data-editor').first().locator('.pane-heading span')).toContainText(`${size.toLocaleString('en-US')} / 16,777,216 bytes`)
})

test('file selection imports automatically and preserves the opposite side across reloads', async ({ page }, testInfo) => {
  async function select(label: string, files: Record<string, string | Buffer>, invalid = false) {
    const chooser = page.waitForEvent('filechooser')
    await page.getByRole('button', { name: `${label}を選択`, exact: true }).click()
    const picker = await chooser
    expect(picker.isMultiple()).toBe(true)
    await picker.setFiles(Object.entries(files).map(([name, content]) => ({ name, mimeType: 'text/plain', buffer: Buffer.isBuffer(content) ? content : Buffer.from(content) })))
    if (invalid) await expect(page.locator('.test-case-editor [role=alert]')).toBeVisible()
    else await expect(page.locator('.test-case-editor [role=status]')).toContainText('件更新しました。')
    await expect(page.getByRole('button', { name: `${label}を選択`, exact: true })).toBeEnabled()
  }
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByText('ファイルから一括追加', { exact: true }).click()
  await expect(page.getByRole('button', { name: '一括追加', exact: true })).toHaveCount(0)
  for (const input of await page.locator('.bulk-import input[type=file]').all()) {
    await expect(input).toBeHidden()
    await expect(input).not.toHaveAttribute('webkitdirectory')
    await expect(input).toHaveAttribute('accept', '.txt,text/plain')
  }
  await select('入力ファイル', { 'sum.txt': '3 5\n', 'empty.txt': '' })
  await expect(page.locator('.case-files li')).toHaveCount(2)
  await page.getByRole('button', { name: 'sum.txt', exact: true }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('3 5')
  await expect(page.getByLabel('出力', { exact: true })).toBeEmpty()
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByText('ファイルから一括追加', { exact: true }).click()
  await select('出力ファイル', { 'sum.txt': '8\n', 'output-first.txt': '42' })
  await expect(page.locator('.case-files li')).toHaveCount(3)
  await page.getByRole('button', { name: 'sum.txt', exact: true }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('3 5')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('8')
  await select('入力ファイル', { 'output-first.txt': '21' })
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('21')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('42')
  // Updating output later must preserve both the imported and manually edited input.
  await page.getByRole('button', { name: 'sum.txt', exact: true }).click()
  await page.getByLabel('入力', { exact: true }).fill('9')
  await select('出力ファイル', { 'sum.txt': '18' })
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('9')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('18')
  const batches = [
    { files: { 'bad.txt': Buffer.from([0xff]) }, error: 'UTF-8' },
    { files: { 'bad.txt': '\0' }, error: '使用できない文字' },
    { files: { 'bad.csv': '' }, error: '.txt' },
    { files: { 'big.txt': Buffer.alloc(16 * 1024 * 1024 + 1) }, error: '16 MiB' },
    { files: Object.fromEntries(Array.from({ length: 99 }, (_, i) => [`case${i}.txt`, ''])), error: '100件' },
  ]
  for (const item of batches) {
    await select('入力ファイル', item.files, true)
    await expect(page.locator('.test-case-editor [role=alert]')).toContainText(item.error)
    await expect(page.locator('.case-files li')).toHaveCount(3)
    await expect(page.getByLabel('入力', { exact: true })).toHaveText('9')
    await expect(page.getByLabel('出力', { exact: true })).toHaveText('18')
  }
  await select('入力ファイル', { 'sum.txt': '10' })
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('18')
  for (const width of [320, 375, 414, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.getByRole('button', { name: '入力ファイルを選択', exact: true })).toBeInViewport()
    await expect(page.getByRole('button', { name: '出力ファイルを選択', exact: true })).toBeInViewport()
    if (width === 375 || width === 1280) await page.screenshot({ path: testInfo.outputPath(`file-import-${width}.png`), fullPage: true })
  }
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.locator('.case-files li')).toHaveCount(3)
  await page.getByRole('button', { name: 'sum.txt', exact: true }).click()
  await expect(page.getByLabel('入力', { exact: true })).toHaveText('10')
  await expect(page.getByLabel('出力', { exact: true })).toHaveText('18')
})

test('single-side import preserves stored opposite files and validates before mutation', async () => {
  const { importTestCaseFiles, mergeTestCases } = await import('../app/utils/import-test-cases')
  const file = (name: string, value = '') => new File([value], name)
  const storedFile = { id: '33333333-3333-4333-8333-333333333333', size: 16 << 20, sha256: 'a'.repeat(64) }
  const existing = Array.from({ length: 100 }, (_, i) => ({ name: `${i}.txt`, input: '', output: '', isSample: i === 0, ...(i < 16 ? { inputFile: storedFile, outputFile: storedFile } : {}) }))
  const snapshot = JSON.stringify(existing)
  const imported = await importTestCaseFiles([file('0.txt', '9')], 'input', existing)
  const merged = mergeTestCases(existing, imported, ['input'])
  expect(merged).toHaveLength(100)
  expect(merged[0]).toEqual({ name: '0.txt', isSample: true, input: '9', output: '', outputFile: storedFile })
  expect(merged.slice(1)).toEqual(existing.slice(1))
  const outputs = await importTestCaseFiles([file('0.txt', '18')], 'output', merged)
  expect(mergeTestCases(merged, outputs, ['output'])[0]).toEqual({ name: '0.txt', isSample: true, input: '9', output: '18' })
  await expect(importTestCaseFiles([file('0.txt', '\0')], 'input', existing)).rejects.toThrow('使用できない文字')
  await expect(importTestCaseFiles([file('0.txt'), file('0.txt')], 'input', existing)).rejects.toThrow('重複')
  // The retained output bytes count toward the combined limit.
  await expect(importTestCaseFiles([file('99.txt', '1')], 'input', existing)).rejects.toThrow('512 MiB')
  expect(JSON.stringify(existing)).toBe(snapshot)
})


test('sample checkbox controls the blue flag, survives rename and reload, and can be cleared', async ({ page }) => {
  await page.goto('/problems/new')
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByLabel('テストケース名 1', { exact: true }).fill('custom.txt')
  const checkbox = page.getByRole('checkbox', { name: 'サンプルケースにする' })
  await expect(checkbox).not.toBeChecked()
  await checkbox.check()
  const flag = page.getByRole('img', { name: 'サンプルケース', exact: true })
  await expect(flag).toBeVisible()
  await expect(flag).toHaveCSS('fill', 'rgb(36, 99, 212)')
  await page.getByLabel('テストケース名 1', { exact: true }).fill('renamed.txt')
  await expect(checkbox).toBeChecked()
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(checkbox).toBeChecked()
  await expect(flag).toBeVisible()
  await page.getByLabel('テストケース名 1', { exact: true }).fill('sample_unchecked.txt')
  await checkbox.uncheck()
  await expect(flag).toHaveCount(0)
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(checkbox).not.toBeChecked()
  await expect(flag).toHaveCount(0)
})

test('append samples preserves the statement, excludes private cases, and saves literal data', async ({ page }) => {
  await page.goto('/problems/new')
  await expect(page.locator('#problem-source')).not.toHaveText(/^## サンプル/m, { useInnerText: true })
  const original = '## 問題文\n\n既存の本文\n\n## サンプル 1\n'
  await page.locator('#problem-source').fill(original)
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  const append = page.getByRole('button', { name: 'サンプルを問題文に追加', exact: true })
  await expect(append).toBeDisabled()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByLabel('入力', { exact: true }).fill('private input')
  await expect(append).toBeDisabled()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByRole('checkbox', { name: 'サンプルケースにする' }).check()
  await page.getByLabel('入力', { exact: true }).fill('3 5\n```\n$literal$')
  await page.getByLabel('出力', { exact: true }).fill('8')
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByRole('checkbox', { name: 'サンプルケースにする' }).check()
  await append.click()
  await expect(page.getByText('2件のサンプルを問題文の末尾に追加しました。')).toBeVisible()
  await page.getByRole('button', { name: '問題文', exact: true }).click()
  const expected = original + '\n\n## サンプル 2\n\n### 入力\n````text\n3 5\n```\n$literal$\n````\n\n### 出力\n```text\n8\n```\n\n## サンプル 3\n\n### 入力\n```text\n```\n\n### 出力\n```text\n```\n'
  await expect(page.locator('#problem-source')).toHaveText(expected, { useInnerText: true })
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  await page.reload()
  await expect(page.locator('#problem-source')).toHaveText(expected, { useInnerText: true })
  await page.locator('#problem-source').fill('a'.repeat(100_000))
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await append.click()
  await expect(page.getByRole('alert').filter({ hasText: '100,000文字を超えます' })).toBeVisible()
  await page.getByRole('button', { name: '問題文', exact: true }).click()
  await expect(page.locator('.source-pane .pane-heading')).toContainText('100,000 / 100,000')
  await expect(page.getByRole('status').filter({ hasText: /^保存済み$/ })).toBeVisible()
  // CodeMirror virtualizes long lines; verify the complete saved document instead of its viewport.
  const id = new URL(page.url()).searchParams.get('problem')
  const saved = await page.evaluate(async id => (await (await fetch(`/api/my/problems/${id}`)).json()).draft.markdown, id)
  expect(saved === 'a'.repeat(100_000)).toBe(true)
})
