import { expect, test, type Page } from '@playwright/test'
import { randomUUID } from 'node:crypto'

const origin = 'http://127.0.0.1:13002'
async function login(page: Page, name = 'alice') {
  await page.goto('/login')
  await page.getByLabel('メールアドレス').fill(`${name}@example.test`)
  await page.getByLabel('パスワード', { exact: true }).fill('test-password')
  await page.getByRole('button', { name: 'ログイン', exact: true }).click()
  await expect(page).toHaveURL('/my')
}
async function seed(page: Page, title: string) {
  const id = randomUUID()
  const response = await page.request.put(`/api/my/problems/${id}`, { headers: { origin }, data: { version: 0, draft: { title, markdown: '## コンテスト本文\n整数を出力してください。', editorial: '## コンテスト解説\n答えは2です。', timeLimitMs: '1000', memoryLimitMb: '512', testCases: [{ input: '1', output: '2', isSample: true }] } } })
  expect(response.status()).toBe(200)
  return id
}
function localDate(value: number) {
  const date = new Date(value)
  return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16)
}

test('create, reorder and edit an unpublished contest; guests cannot inspect its problems', async ({ page, browser }, testInfo) => {
  // This covers creation, editing and multiple viewport checks against the real DB.
  test.slow()
  await login(page)
  const first = await seed(page, 'コンテスト選択A')
  const second = await seed(page, 'コンテスト選択B')
  await page.goto('/my')
  const tabs = page.getByRole('navigation', { name: 'マイページのコンテンツ' })
  await expect(tabs.getByRole('button')).toHaveText(['自分の問題', 'テスト中の問題', '記事', 'コンテスト', '提出履歴', 'イベント'])
  await tabs.getByRole('button', { name: 'コンテスト', exact: true }).click()
  await expect(page.getByRole('heading', { name: '作成したコンテスト', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '新規コンテスト', exact: true }).click()
  await expect(page.locator('.site-shell--editor')).toBeVisible()
  await page.getByLabel('コンテストタイトル', { exact: true }).fill('ブラウザ作成コンテスト')
  await page.getByLabel('説明（Markdown）').fill('## 開催案内\nどなたでも参加できます。')
  await expect(page.locator('.contest-preview')).toContainText('開催案内')
  // Saving from another section reveals the missing field instead of focusing a hidden input.
  await page.getByRole('button', { name: 'コンテストを作成', exact: true }).click()
  await expect(page.getByRole('button', { name: 'コンテスト設定', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByLabel('開始日時')).toBeFocused()
  await expect(page.getByLabel('誤答ペナルティ（分）')).toHaveValue('5')
  await page.getByLabel('開始日時').fill(localDate(Date.now() + 86400000))
  await page.getByLabel('終了日時').fill(localDate(Date.now() + 90000000))
  await page.getByRole('button', { name: '問題・配点', exact: true }).click()
  await page.getByRole('checkbox', { name: 'コンテスト選択A', exact: true }).check()
  await page.getByRole('checkbox', { name: 'コンテスト選択B', exact: true }).check()
  await page.locator(`#points-${first}`).fill('300')
  await page.getByRole('button', { name: 'コンテスト選択Bを上へ' }).click()
  await page.getByRole('button', { name: 'タイトル・説明', exact: true }).click()
  await expect(page.getByLabel('説明（Markdown）')).toHaveText('## 開催案内\nどなたでも参加できます。', { useInnerText: true })
  await page.screenshot({ path: testInfo.outputPath('contest-editor-desktop.png'), fullPage: true })
  for (const width of [320, 375, 414, 768]) {
    await page.setViewportSize({ width, height: 900 })
    for (const name of ['タイトル・説明', '問題・配点', 'コンテスト設定']) {
      await page.getByRole('button', { name, exact: true }).click()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      if (width === 375) await page.screenshot({ path: testInfo.outputPath(`contest-${name}-mobile.png`), fullPage: true })
    }
    await page.getByRole('button', { name: 'サイドバーを展開', exact: true }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'サイドバーを折りたたむ', exact: true }).click()
  }
  await page.getByRole('button', { name: 'コンテストを作成', exact: true }).click()
  await expect(page).toHaveURL(/\/contests\/[a-f0-9-]{36}$/)
  const id = page.url().split('/').pop()!
  const saved = await (await page.request.get(`/api/my/contests/${id}`)).json()
  expect(saved.problems.map((p: { id: string }) => p.id)).toEqual([second, first])
  expect(saved.penaltyMinutes).toBe(5)
  expect(saved.status).toBe('draft')
  const anonymous = await browser.newContext({ baseURL: origin })
  expect((await anonymous.request.get(`/api/contests/${id}`)).status()).toBe(404)
  expect((await (await anonymous.request.get('/api/contests')).json()).items.some((c: { id: string }) => c.id === id)).toBe(false)
  await expect(page.getByText('このコンテストは未公開です。編集画面の「投稿」で公開できます。')).toBeVisible()

  await expect(page.getByRole('heading', { name: '開催案内', exact: true })).toBeVisible()
  const contestMenu = page.getByRole('navigation', { name: 'コンテストメニュー' })
  for (const width of [1280, 320, 375, 414, 768]) {
    await page.setViewportSize({ width, height: 900 })
    for (const name of ['概要', '問題', '順位表', '提出一覧']) {
      await contestMenu.getByRole('link', { name, exact: true }).click()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await page.screenshot({ path: testInfo.outputPath(`contest-${name}-${width}.png`), fullPage: true })
    }
  }
  await contestMenu.getByRole('link', { name: '順位表', exact: true }).click()
  await expect(page).toHaveURL(`/contests/${id}?view=standings`)
  await expect(contestMenu.getByRole('link', { name: '順位表', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('heading', { name: '公式順位表', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '開催案内', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: '公式順位表', exact: true })).toBeVisible()
  await contestMenu.getByRole('link', { name: '問題', exact: true }).click()
  await expect(page.getByRole('region', { name: 'コンテストの問題', exact: true })).toContainText('コンテスト選択A')
  await expect(page.getByRole('heading', { name: '公式順位表', exact: true })).toHaveCount(0)
  await contestMenu.getByRole('link', { name: '提出一覧', exact: true }).click()
  await expect(page.getByText('提出はまだありません。', { exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'コンテストの問題', exact: true })).toHaveCount(0)
  await page.goBack()
  await expect(page).toHaveURL(`/contests/${id}?view=problems`)
  await expect(page.getByRole('region', { name: 'コンテストの問題', exact: true })).toBeVisible()
  await contestMenu.getByRole('link', { name: '概要', exact: true }).click()
  await expect(page.getByRole('heading', { name: '開催案内', exact: true })).toBeVisible()
  await expect(contestMenu.getByRole('link', { name: 'ルール', exact: true })).toHaveCount(0)
  await page.getByRole('region', { name: '概要', exact: true }).getByRole('link', { name: 'ルール', exact: true }).click()
  await expect(page).toHaveURL('/blog/contest-rules')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('コンテストのルール')
  await page.getByRole('link', { name: '使える言語と実行環境の仕様', exact: true }).click()
  await expect(page).toHaveURL('/blog/language-guide')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('使える言語と実行環境の仕様')
  for (const width of [320, 375, 414, 768]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`language-guide-${width}.png`), fullPage: true })
  }
  await page.goBack()
  for (const width of [320, 375, 414, 768]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`contest-rules-${width}.png`), fullPage: true })
  }
  await page.goBack()
  await page.getByRole('link', { name: 'コンテストを編集', exact: true }).click()
  await page.getByRole('button', { name: 'コンテスト設定', exact: true }).click()
  await page.getByLabel('誤答ペナルティ（分）').fill('0')
  await page.getByRole('button', { name: '変更を保存' }).click()
  await expect(page.getByText('誤答ペナルティ 0 分 · 部分点なし')).toBeVisible()
  await page.goto('/my/contests')
  await expect(page).toHaveURL('/my?tab=contests')
  await expect(page.getByRole('button', { name: 'コンテスト', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('link', { name: 'ブラウザ作成コンテスト', exact: true })).toBeVisible()
  for (const width of [320, 375, 414, 768]) {
    await page.setViewportSize({ width, height: 900 })
    await expect(tabs.getByRole('button', { name: 'コンテスト', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (width === 375) await page.screenshot({ path: testInfo.outputPath('my-contests-mobile.png'), fullPage: true })
  }
  expect((await anonymous.request.get(`/api/contests/${id}`)).status()).toBe(404)
  await page.goto(`/my/contests/${id}`)
  await page.getByRole('button', { name: '投稿', exact: true }).click()
  await expect(page).toHaveURL(`/contests/${id}`)
  expect((await anonymous.request.get(`/api/contests/${id}`)).status()).toBe(200)
  await anonymous.close()
  await page.goto('/contests')
  await expect(page.locator('main').getByRole('link', { name: '新規コンテスト', exact: true })).toHaveAttribute('href', '/my/contests/new')
  const guest = await browser.newContext({ baseURL: origin })
  const reader = await guest.newPage()
  await reader.goto(`/contests/${id}`)
  await expect(reader.getByRole('heading', { name: 'ブラウザ作成コンテスト' })).toBeVisible()
  await reader.getByRole('navigation', { name: 'コンテストメニュー' }).getByRole('link', { name: '問題', exact: true }).click()
  await expect(reader.getByText('問題は開始時刻に公開されます。事前に閲覧できるのは作成者と、その問題のテスターです。')).toBeVisible()
  await expect(reader.getByRole('link', { name: 'コンテスト選択A', exact: true })).toHaveCount(0)
  expect((await guest.request.get(`/api/contests/${id}/problems/${first}`)).status()).toBe(404)
  expect((await guest.request.get(`/api/problems/${first}`)).status()).toBe(404)
  const csrf = await page.request.put(`/api/my/contests/${id}`, { headers: { origin: 'https://attacker.example' }, data: {} })
  expect(csrf.status()).toBe(403)
  await guest.close()
})

test('scheduled problems open for submission, then publish with editorial and source after the deadline', async ({ page, browser }, testInfo) => {
  test.setTimeout(75000)
  await login(page)
  const pid = await seed(page, '時間で公開する問題')
  const participant = await browser.newContext({ baseURL: origin })
  const bob = await participant.newPage()
  await login(bob, 'bob')
  const guest = await browser.newContext({ baseURL: origin })
  const id = randomUUID()
  const now = Date.now()
  const response = await page.request.put(`/api/my/contests/${id}`, { headers: { origin }, data: { publish: true, title: '自動公開コンテスト', description: '', startsAt: new Date(now + 4000).toISOString(), endsAt: new Date(now + 30000).toISOString(), version: 0, problems: [{ id: pid, points: 100 }] } })
  expect(response.status()).toBe(200)
  expect((await guest.request.get(`/api/contests/${id}/problems/${pid}`)).status()).toBe(404)
  await page.goto(`/contests/${id}/problems/${pid}`)
  const authorMenu = page.getByRole('navigation', { name: '問題メニュー' })
  await expect(authorMenu.getByRole('link', { name: '解説', exact: true })).toBeVisible()
  await expect(authorMenu.getByRole('link', { name: '順位表', exact: true })).toHaveCount(0)
  await expect.poll(async () => (await guest.request.get(`/api/contests/${id}/problems/${pid}`)).status(), { timeout: 10000 }).toBe(200)
  const live = await (await guest.request.get(`/api/contests/${id}/problems/${pid}`)).json()
  expect(live.editorial).toBeUndefined()
  await bob.goto(`/contests/${id}/problems/${pid}`)
  await expect(bob.getByRole('heading', { name: 'コンテスト本文', exact: true })).toBeVisible()
  await expect(bob.getByRole('navigation', { name: '問題メニュー' }).getByRole('link')).toHaveText(['問題', '自分の提出', 'すべての提出'])
  await bob.getByLabel('ソースコード', { exact: true }).fill('int main(){}')
  const guideOpened = bob.waitForEvent('popup')
  await bob.getByRole('link', { name: '使える言語と実行環境の仕様' }).click()
  const guide = await guideOpened
  await expect(guide).toHaveURL('/blog/language-guide')
  await expect(guide.getByRole('heading', { level: 1 })).toHaveText('使える言語と実行環境の仕様')
  await guide.close()
  await expect(bob.getByLabel('ソースコード', { exact: true })).toHaveText('int main(){}')
  await bob.getByRole('button', { name: '提出する', exact: true }).click()
  await expect(bob).toHaveURL(/\/my\/submissions\/[a-f0-9-]{36}$/)
  const sid = bob.url().split('/').pop()!
  const setterSubmission = await page.request.post('/api/my/submissions', { headers: { origin }, data: { problemId: pid, contestId: id, runtime: 'cpp17', source: 'int main(){return 0;}' } })
  expect(setterSubmission.status()).toBe(202)
  await expect(bob.getByRole('link', { name: '時間で公開する問題', exact: true })).toHaveAttribute('href', `/contests/${id}/problems/${pid}`)
  expect((await guest.request.get(`/api/contests/${id}/submissions/${sid}`)).status()).toBe(404)
  await bob.getByRole('link', { name: '時間で公開する問題', exact: true }).click()
  const bobMenu = bob.getByRole('navigation', { name: '問題メニュー' })
  await bobMenu.getByRole('link', { name: '自分の提出', exact: true }).click()
  await expect(bob).toHaveURL(`/contests/${id}/problems/${pid}?view=my-submissions`)
  await expect(bob.getByRole('region', { name: '自分の提出', exact: true })).toContainText('bob')
  await expect(bob.getByRole('region', { name: '自分の提出', exact: true })).not.toContainText('alice')
  await bob.getByRole('link', { name: '詳細', exact: true }).click()
  await bob.getByRole('link', { name: 'この問題の自分の提出', exact: true }).click()
  await bobMenu.getByRole('link', { name: 'すべての提出', exact: true }).click()
  await expect(bob.getByText('すべての提出はコンテスト終了後に公開されます。終了前はコンテストセッターとテスターが閲覧できます。')).toBeVisible()
  expect((await bob.request.get(`/api/contests/${id}/problems/${pid}/submissions`)).status()).toBe(404)
  await authorMenu.getByRole('link', { name: 'すべての提出', exact: true }).click()
  await expect(page.getByRole('region', { name: 'すべての提出', exact: true })).toContainText('bob')
  await page.getByRole('region', { name: 'すべての提出', exact: true }).getByRole('row').filter({ hasText: 'bob' }).getByRole('link', { name: '詳細' }).click()
  await expect(page.getByRole('textbox', { name: 'ソースコード', exact: true })).toHaveText('int main(){}')
  const reader = await guest.newPage()
  await reader.goto(`/contests/${id}/problems/${pid}`)
  await expect(reader.getByRole('navigation', { name: '問題メニュー' }).getByRole('link')).toHaveText(['問題', '自分の提出', 'すべての提出'])
  await reader.goto(`/contests/${id}?view=standings`)
  await expect(reader.getByRole('region', { name: '公式順位表', exact: true })).toContainText('bob')
  await reader.setViewportSize({ width: 375, height: 900 })
  expect(await reader.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await reader.screenshot({ path: testInfo.outputPath('contest-standings-mobile.png'), fullPage: true })
  await expect.poll(async () => (await guest.request.get(`/api/problems/${pid}`)).status(), { timeout: 35000 }).toBe(200)
  await reader.goto(`/contests/${id}/problems/${pid}?view=editorial`)
  await expect(reader.getByRole('heading', { name: 'コンテスト解説', exact: true })).toBeVisible()
  await expect(reader.getByRole('navigation', { name: '問題メニュー' }).getByRole('link', { name: '解説', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(reader.getByRole('navigation', { name: '問題メニュー' }).getByRole('link')).toHaveText(['問題', '解説', '自分の提出', 'すべての提出'])
  for (const width of [320, 375, 414, 768]) {
    await reader.setViewportSize({ width, height: 900 })
    expect(await reader.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await reader.screenshot({ path: testInfo.outputPath(`contest-editorial-${width}.png`), fullPage: true })
  }
  await reader.goto(`/contests/${id}/submissions/${sid}`)
  await expect(reader.getByRole('textbox', { name: 'ソースコード', exact: true })).toHaveText('int main(){}')
  for (const width of [320, 375, 414, 768]) {
    await reader.setViewportSize({ width, height: 900 })
    expect(await reader.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await reader.screenshot({ path: testInfo.outputPath(`contest-submission-${width}.png`), fullPage: true })
  }
  await reader.getByRole('navigation', { name: '提出メニュー' }).getByRole('link', { name: '提出一覧', exact: true }).click()
  await expect(reader).toHaveURL(`/contests/${id}?view=submissions`)
  await expect(reader.getByRole('region', { name: '提出一覧', exact: true })).toContainText('bob')
  await reader.getByRole('row').filter({ hasText: 'bob' }).getByRole('link', { name: '時間で公開する問題', exact: true }).click()
  await expect(reader).toHaveURL(`/contests/${id}/submissions/${sid}`)
  await reader.goto(`/contests/${id}?view=problems`)
  await expect(reader.getByRole('region', { name: 'コンテストの問題', exact: true })).toBeVisible()
  await reader.goto(`/contests/${id}/problems/${pid}?view=submissions`)
  await expect(reader.getByRole('region', { name: 'すべての提出', exact: true })).toContainText('alice')
  await expect(reader.getByRole('region', { name: 'すべての提出', exact: true })).toContainText('bob')
  await reader.goto(`/problems/${pid}?view=submissions`)
  await expect(reader.getByRole('region', { name: 'すべての提出', exact: true })).toContainText('bob')
  await reader.getByRole('row').filter({ hasText: 'bob' }).getByRole('link', { name: '詳細' }).click()
  await expect(reader).toHaveURL(`/problems/${pid}/submissions/${sid}`)
  await expect(reader.getByRole('textbox', { name: 'ソースコード', exact: true })).toHaveText('int main(){}')
  await reader.getByRole('link', { name: 'この問題のすべての提出', exact: true }).click()
  await bob.goto(`/problems/${pid}?view=my-submissions`)
  await expect(bob.getByRole('region', { name: '自分の提出', exact: true })).toContainText('bob')
  await expect(bob.getByRole('region', { name: '自分の提出', exact: true })).not.toContainText('alice')
  await bob.getByRole('link', { name: '詳細', exact: true }).click()
  await bob.getByRole('link', { name: 'この問題の自分の提出', exact: true }).click()
  await expect(bob).toHaveURL(`/problems/${pid}?view=my-submissions`)
  for (const width of [320, 375, 414, 768]) {
    await bob.setViewportSize({ width, height: 900 })
    expect(await bob.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await bob.screenshot({ path: testInfo.outputPath(`problem-submissions-${width}.png`), fullPage: true })
  }
  await guest.close()
  await participant.close()
})
