import { request as httpRequest } from 'node:http'
import { expect, test, type Page } from '@playwright/test'

async function login(page: Page, username = 'alice@example.test') {
  await page.goto('/login')
  await page.getByLabel('メールアドレス').fill(username)
  await page.getByLabel('パスワード', { exact: true }).fill('test-password')
  await page.getByRole('button', { name: 'ログイン', exact: true }).click()
  await expect(page).toHaveURL('/my')
}

test('login, database save, another browser, ownership, conflict and logout', async ({ page, browser }) => {
  await login(page)
  const cookie = (await page.context().cookies()).find(c => c.name === 'openoj_access')!
  expect(cookie.httpOnly).toBe(true)
  expect(cookie.sameSite).toBe('Lax')
  expect(await page.evaluate(() => document.cookie)).not.toContain('openoj_access')
  await page.getByRole('main').getByRole('link', { name: '新規問題' }).click()
  await page.locator('#problem-title').fill('DBで保存した問題')
  await page.locator('#problem-source').fill('## 永続化した本文\n$A+B$')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('保存済み')
  await expect(page).toHaveURL(/problem=/)
  const editorURL = page.url()
  const id = new URL(editorURL).searchParams.get('problem')!
  expect(id).toBeTruthy()
  expect(await page.evaluate(() => Object.keys(localStorage).filter(k => k.startsWith('openoj.problem-drafts')))).toEqual([])
  await page.getByRole('link', { name: 'ShareOJ マイページ', exact: true }).click()
  await expect(page).toHaveURL('/my')
  await expect(page.getByRole('link', { name: 'DBで保存した問題を編集', exact: true })).toBeVisible()

  const secondContext = await browser.newContext({ baseURL: 'http://127.0.0.1:13002' })
  const second = await secondContext.newPage()
  await login(second)
  await second.getByRole('link', { name: 'DBで保存した問題を編集', exact: true }).click()
  await expect(second.locator('#problem-source')).toHaveText('## 永続化した本文\n$A+B$', { useInnerText: true })
  await page.goto(editorURL)
  await expect(page.locator('#problem-title')).toHaveValue('DBで保存した問題')
  await second.locator('#problem-title').fill('別のブラウザーから再編集')
  await expect(second.getByRole('status')).toHaveText('保存済み')
  await page.locator('#problem-title').fill('競合する編集を保持')
  await expect(page.getByRole('alert')).toContainText('別の画面で更新されています')
  await expect(page.locator('#problem-title')).toHaveValue('競合する編集を保持')
  const response = await second.request.get(`/api/my/problems/${id}`)
  expect((await response.json()).draft.title).toBe('別のブラウザーから再編集')
  const csrf = await second.request.put(`/api/my/problems/${id}`, { headers: { origin: 'https://attacker.example' }, data: {} })
  expect(csrf.status()).toBe(403)
  const unauthContext = await browser.newContext({ baseURL: 'http://127.0.0.1:13002' })
  expect((await unauthContext.request.get(`/api/my/problems/${id}`)).status()).toBe(401)
  const bob = await unauthContext.newPage()
  await login(bob, 'bob@example.test')
  await expect(bob.getByRole('link', { name: /別のブラウザーから再編集/ })).toHaveCount(0)
  expect((await bob.request.get(`/api/my/problems/${id}`)).status()).toBe(404)
  await bob.goto(`/problems/new?problem=${id}`)
  await expect(bob.getByRole('alert')).toContainText('アクセスできません')
  await expect(bob.locator('#problem-title')).toBeDisabled()

  await second.context().clearCookies()
  await second.locator('#problem-title').fill('期限切れでも内容を残す')
  await expect(second.getByRole('alert')).toContainText('ログイン')
  await expect(second.locator('#problem-title')).toHaveValue('期限切れでも内容を残す')
  const reauth = await secondContext.newPage()
  await login(reauth)
  await reauth.close()
  await second.bringToFront()
  await second.getByRole('button', { name: '保存', exact: true }).click()
  await expect(second.getByRole('status')).toHaveText('保存済み')
  expect((await (await second.request.get(`/api/my/problems/${id}`)).json()).draft.title).toBe('期限切れでも内容を残す')
  await unauthContext.close(); await secondContext.close()
})

test('DB-only library ignores legacy drafts, refreshes cache and deletes the saved problem', async ({ page }) => {
  await page.goto('/problems/new')
  await expect(page).toHaveURL(/login/)
  await login(page)
  await page.evaluate(() => localStorage.setItem('openoj.problem-drafts.v2.legacy', JSON.stringify({ title: '旧ローカル下書き' })))
  await page.reload()
  await expect(page.getByText('このブラウザーの下書き', { exact: true })).toHaveCount(0)
  await expect(page.getByText('アカウントに保存した問題', { exact: true })).toHaveCount(0)
  await page.getByRole('main').getByRole('link', { name: '新規問題' }).click()
  await page.locator('#problem-title').fill('キャッシュ対象の問題')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('保存済み')
  await expect(page).toHaveURL(/problem=/)
  const url = page.url()
  const id = new URL(url).searchParams.get('problem')!
  expect(await page.evaluate(() => Object.keys(sessionStorage).some(k => k.startsWith('openoj.problem-cache.v1.')))).toBe(true)
  const current = await (await page.request.get(`/api/my/problems/${id}`)).json()
  const updated = await page.request.put(`/api/my/problems/${id}`, { headers: { origin: 'http://127.0.0.1:13002' }, data: { version: current.version, draft: { ...current.draft, title: 'DBが最新' } } })
  expect(updated.ok()).toBe(true)
  await page.reload()
  await expect(page.locator('#problem-title')).toHaveValue('DBが最新')
  await expect(page.locator('#problem-title')).toBeEnabled()
  await page.route('**/api/my/problems/*', route => route.abort())
  await page.locator('#problem-title').fill('保存に失敗する変更')
  await expect(page.getByRole('status')).toHaveText('保存に失敗しました')
  expect(await page.evaluate(() => Object.values(sessionStorage).some(v => v.includes('保存に失敗する変更')))).toBe(false)
  await page.unroute('**/api/my/problems/*')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('保存済み')
  await page.getByRole('button', { name: '問題管理', exact: true }).click()
  await page.getByRole('button', { name: '問題を削除', exact: true }).click()
  await page.getByRole('button', { name: '削除する', exact: true }).click()
  await expect(page).toHaveURL('/my?tab=problems')
  expect((await page.request.get(`/api/my/problems/${id}`)).status()).toBe(404)
  expect(await page.evaluate(id => Object.keys(sessionStorage).some(k => k.endsWith(id)), id)).toBe(false)
  await page.locator('.site-header').getByRole('button', { name: 'アカウントメニュー', exact: true }).click()
  await page.getByRole('navigation', { name: 'アカウント', exact: true }).getByRole('button', { name: 'ログアウト', exact: true }).click()
  await expect(page).toHaveURL('/login')
})

test('rejects oversized chunked writes without saving a problem', async ({ page }) => {
  await login(page)
  const cookies = (await page.context().cookies()).map(c => `${c.name}=${c.value}`).join('; ')
  const id = '55555555-5555-4555-8555-555555555555'
  const status = await new Promise<number | undefined>((resolve, reject) => {
    const request = httpRequest(`http://127.0.0.1:13002/api/my/problems/${id}`, {
      method: 'PUT', headers: { cookie: cookies, origin: 'http://127.0.0.1:13002', 'content-type': 'application/json' },
    }, response => { response.resume(); response.on('end', () => resolve(response.statusCode)) })
    request.on('error', reject)
    request.write(JSON.stringify({ version: 0, draft: { markdown: 'x'.repeat(4 * 1024 * 1024) } }))
    request.end()
  })
  expect(status).toBe(413)
  expect((await page.request.get(`/api/my/problems/${id}`)).status()).toBe(404)
})
