import { expect, test, type Page } from '@playwright/test'
async function login(page: Page) {
  await page.goto('/login')
  await page.getByLabel('メールアドレス').fill('alice@example.test')
  await page.getByLabel('パスワード', { exact: true }).fill('test-password')
  await page.getByRole('button', { name: 'ログイン', exact: true }).click()
  await expect(page).toHaveURL('/my')
  page.on('dialog', dialog => dialog.accept())
}
test('problem publication is visible anonymously and private edits stay private', async ({ page, browser }, testInfo) => {
  await login(page)
  await page.goto('/problems/new')
  await page.locator('#problem-title').fill('公開フロー確認')
  await page.getByRole('combobox', { name: '難易度（作成者設定）' }).click()
  await page.getByRole('option', { name: 'Lv.4', exact: true }).click()
  await page.locator('#problem-source').fill('## 公開本文\n$A+B$')
  await page.getByRole('button', { name: '解説', exact: true }).click()
  await page.locator('#problem-source').fill('## 公開解説\n$A+B$ を計算します。')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page).toHaveURL(/problem=/)
  await expect(page.getByRole('status')).toHaveText('保存済み')
  const id = new URL(page.url()).searchParams.get('problem')!
  const guest = await browser.newContext({ baseURL: 'http://127.0.0.1:13002' })
  expect((await guest.request.get(`/api/problems/${id}`)).status()).toBe(404)
  await page.getByRole('button', { name: '問題管理', exact: true }).click()
  await page.goto('/problems')
  await page.getByRole('button', { name: '問題投稿', exact: true }).click()
  await page.getByLabel('投稿する問題').selectOption(id)
  await page.getByRole('dialog').getByRole('button', { name: '投稿', exact: true }).click()
  await expect(page).toHaveURL(`/problems/${id}`)
  const reader = await guest.newPage()
  await reader.goto(`/problems/${id}`)
  await expect(reader.getByRole('heading', { level: 1 })).toHaveText('公開フロー確認')
  await expect(reader.locator('.katex')).toBeVisible()
  await expect(reader.getByText('Lv.4')).toBeVisible()
  for (const width of [320, 375, 414, 768]) {
    await reader.setViewportSize({ width, height: 900 })
    expect(await reader.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await reader.screenshot({ path: testInfo.outputPath(`problem-${width}.png`), fullPage: true })
  }
  const savedEditorURL = `/problems/new?problem=${id}`
  const favoritePage = await page.context().newPage()
  await favoritePage.goto(`/problems/${id}`)
  const favorite = favoritePage.getByRole('button', { name: /お気に入り/ })
  await expect(favorite).toBeEnabled()
  await favorite.click()
  await expect(favorite).toHaveAttribute('aria-pressed', 'true')
  await favoritePage.reload()
  await expect(favorite).toHaveAttribute('aria-pressed', 'true')
  const listing = await (await guest.request.get('/api/problems')).json()
  expect(listing.items.find((p: { id: string }) => p.id === id)).toMatchObject({ difficulty: 4, favoriteCount: 1, timeLimitMs: 2000, memoryLimitMb: 512 })
  const csrf = await favoritePage.request.put(`/api/my/favorites/${id}`, { headers: { origin: 'https://attacker.example' }, data: { favorited: false } })
  expect(csrf.status()).toBe(403)
  await favorite.click()
  await expect(favorite).toHaveAttribute('aria-pressed', 'false')
  const vote = favoritePage.getByRole('region', { name: '難易度投票' })
  await vote.getByLabel('あなたの評価').selectOption('7')
  await vote.getByRole('button', { name: '投票する', exact: true }).click()
  await expect(vote).toContainText('Lv.7.0')
  await favoritePage.reload()
  await expect(vote.getByLabel('あなたの評価')).toHaveValue('7')
  const publicVote = await (await guest.request.get(`/api/problems/${id}`)).json()
  expect(publicVote).toMatchObject({ difficulty: 4, difficultyAverage: 7, difficultyVoteCount: 1 })
  expect((await guest.request.put(`/api/my/difficulty-votes/${id}`, { headers: { origin: new URL(favoritePage.url()).origin }, data: { difficulty: 2 } })).status()).toBe(401)
  for (const method of ['PUT', 'DELETE']) {
    const response = await favoritePage.request.fetch(`/api/my/difficulty-votes/${id}`, { method, headers: { origin: 'https://attacker.example' }, data: { difficulty: 2 } })
    expect(response.status()).toBe(403)
  }
  await vote.getByRole('button', { name: '投票を取り消す', exact: true }).click()
  await expect(vote).toContainText('（0票）')
  await favoritePage.close()
  await page.goto(savedEditorURL)
  await expect(page.getByRole('combobox', { name: '難易度（作成者設定）' })).toContainText('Lv.4')
  await reader.getByRole('link', { name: '解説', exact: true }).click()
  await expect(reader.getByRole('heading', { name: '公開解説', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '問題文', exact: true }).click()
  await page.locator('#problem-source').fill('非公開の変更')
  await expect(page.getByRole('status')).toHaveText('未保存の変更があります')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('保存済み')
  expect((await (await guest.request.get(`/api/problems/${id}`)).json()).markdown).toContain('公開本文')
  await page.getByRole('button', { name: '問題管理', exact: true }).click()
  await page.getByRole('button', { name: '非公開に戻す' }).click()
  await expect(page.getByRole('status')).toHaveText('非公開に戻しました')
  expect((await guest.request.get(`/problems/${id}`)).status()).toBe(404)
  await guest.close()
})
test('blog draft, preview, publication, editing and withdrawal', async ({ page, browser }, testInfo) => {
  await login(page)
  await page.goto('/blog/new')
  await page.getByLabel('タイトル', { exact: true }).fill('はじめての記事')
  await page.getByLabel('本文（Markdown）').fill('## 解説\n$x^2$')
  await expect(page.locator('.site-shell--editor')).toBeVisible()
  await expect(page.getByRole('button', { name: '分割', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.post-preview .katex')).toBeVisible()
  await expect(page.getByRole('button', { name: /テストケース|解説|入力形式/ })).toHaveCount(0)
  await expect(page.getByText('実行時間制限', { exact: true })).toHaveCount(0)
  const separator = page.getByRole('separator')
  await separator.focus()
  await page.keyboard.press('ArrowRight')
  await expect(separator).toHaveAttribute('aria-valuenow', '52')
  await page.setViewportSize({ width: 375, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('blog-editor-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: 'プレビュー', exact: true }).click()
  await expect(page.locator('.post-preview .katex')).toBeVisible()
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page).toHaveURL(/post=/)
  const id = new URL(page.url()).searchParams.get('post')!
  const guest = await browser.newContext({ baseURL: 'http://127.0.0.1:13002' })
  expect((await guest.request.get(`/api/posts/${id}`)).status()).toBe(404)
  await page.getByRole('button', { name: '記事管理', exact: true }).click()
  await page.getByRole('button', { name: '公開する', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('公開しました')
  const reader = await guest.newPage()
  await reader.goto('/blog')
  await reader.getByRole('link', { name: 'はじめての記事', exact: true }).click()
  await expect(reader.getByRole('heading', { level: 1 })).toHaveText('はじめての記事')
  await expect(reader.getByText('・運営', { exact: true })).toBeVisible()
  await reader.setViewportSize({ width: 375, height: 900 })
  expect(await reader.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await reader.screenshot({ path: testInfo.outputPath('blog-public-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: '本文', exact: true }).click()
  await page.getByRole('button', { name: '編集', exact: true }).click()
  await page.getByLabel('本文（Markdown）').fill('下書き変更')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('保存済み')
  expect((await (await guest.request.get(`/api/posts/${id}`)).json()).markdown).toContain('解説')
  await page.reload()
  await expect(page.getByLabel('本文（Markdown）')).toHaveText('下書き変更', { useInnerText: true })
  await page.getByRole('button', { name: '記事管理', exact: true }).click()
  await page.getByRole('button', { name: '公開内容を更新' }).click()
  await expect(page.getByRole('status')).toHaveText('公開しました')
  expect((await (await guest.request.get(`/api/posts/${id}`)).json()).markdown).toBe('下書き変更')
  await page.getByRole('button', { name: '非公開に戻す' }).click()
  await expect(page.getByRole('status')).toHaveText('非公開に戻しました')
  expect((await guest.request.get(`/blog/${id}`)).status()).toBe(404)
  await page.getByRole('button', { name: '削除', exact: true }).click()
  await expect(page).toHaveURL('/my?tab=posts')
  expect((await page.request.get(`/api/my/posts/${id}`)).status()).toBe(404)
  await guest.close()
})
