import { expect, test } from '@playwright/test'

test('test cases can be edited, restored, published and used for submission without public disclosure', async ({ page }, testInfo) => {
  await page.goto('/login')
  // Keep the submission quota independent of the contest tests' Alice account.
  await page.getByLabel('メールアドレス').fill('test_cases@example.test')
  await page.getByLabel('パスワード', { exact: true }).fill('test-password')
  await page.getByRole('button', { name: 'ログイン', exact: true }).click()
  await expect(page).toHaveURL('/my')
  page.on('dialog', dialog => dialog.accept())
  await page.goto('/problems/new')
  await page.getByLabel('問題のタイトル').fill('UIからのテスト登録')
  await page.getByRole('combobox', { name: '難易度（作成者設定）' }).click()
  await page.getByRole('option', { name: 'Lv.1', exact: true }).click()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByRole('heading', { name: /^テストケース/ })).toBeVisible()
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByLabel('テストケース名 1', { exact: true }).fill('通常ケース')
  await page.getByLabel('入力', { exact: true }).fill('3 5\n')
  await page.getByLabel('出力', { exact: true }).fill('8\n')
  await page.getByRole('button', { name: 'テストケースを追加' }).click()
  await page.getByLabel('入力', { exact: true }).fill('1000000000 1000000000\n')
  await page.getByLabel('出力', { exact: true }).fill('2000000000\n')
  await page.getByLabel('テストケース名 2', { exact: true }).fill('最大値')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('保存済み')
  const id = new URL(page.url()).searchParams.get('problem')!
  await page.reload()
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await expect(page.getByLabel('テストケース名 1', { exact: true })).toHaveValue('通常ケース')
  await expect(page.getByLabel('入力', { exact: true }).locator('.cm-line')).toHaveText(['3 5', ''])
  await page.getByRole('button', { name: '最大値', exact: true }).click()
  await expect(page.getByLabel('出力', { exact: true }).locator('.cm-line')).toHaveText(['2000000000', ''])
  await expect(page.getByLabel('テストケース名 2', { exact: true })).toHaveValue('最大値')
  const inputBox = (await page.getByLabel('入力', { exact: true }).boundingBox())!
  const outputBox = (await page.getByLabel('出力', { exact: true }).boundingBox())!
  expect(inputBox.x + inputBox.width).toBeLessThan(outputBox.x)
  expect(inputBox.y).toBe(outputBox.y)
  await page.screenshot({ path: testInfo.outputPath('test-cases-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 375, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('test-cases-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: '問題管理', exact: true }).click()
  await page.goto('/problems')
  await page.getByRole('button', { name: '問題投稿', exact: true }).click()
  await page.getByLabel('投稿する問題').selectOption(id)
  await page.getByRole('dialog').getByRole('button', { name: '投稿', exact: true }).click()
  await expect(page).toHaveURL(`/problems/${id}`)
  await page.goto(`/problems/new?problem=${id}`)
  const publicResponse = await page.request.get(`/api/problems/${id}`)
  expect(publicResponse.status()).toBe(200)
  expect(await publicResponse.json()).not.toHaveProperty('testCases')
  const submission = await page.request.post('/api/my/submissions', { headers: { origin: 'http://127.0.0.1:13002' }, data: { problemId: id, runtime: 'cpp17-local', source: 'int main(){}' } })
  expect(submission.status()).toBe(202)
  await page.getByRole('button', { name: 'テストケース', exact: true }).click()
  await page.getByRole('button', { name: '最大値', exact: true }).click()
  await page.getByRole('button', { name: 'ケース2を削除' }).click()
  await expect(page.locator('#case-output-1')).toHaveCount(0)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('保存済み')
  const privateResponse = await page.request.get(`/api/my/problems/${id}`)
  expect((await privateResponse.json()).draft.testCases).toEqual([{ name: '通常ケース', isSample: false, input: '3 5\n', output: '8\n' }])
  await page.getByRole('button', { name: '問題管理', exact: true }).click()
  await page.getByRole('button', { name: '一括削除', exact: true }).click()
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('保存済み')
  await page.getByRole('button', { name: '公開内容を更新' }).click()
  await expect(page.getByRole('status')).toHaveText('公開しました')
  const rejected = await page.request.post('/api/my/submissions', { headers: { origin: 'http://127.0.0.1:13002' }, data: { problemId: id, runtime: 'cpp17-local', source: 'int main(){}' } })
  expect(rejected.status()).toBe(409)
})
